import pgvector.sqlalchemy
"""add embedding to papers

Revision ID: 23f27df4c48c
Revises: e48b8466dc89
Create Date: 2026-03-31 22:02:27.293231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f27df4c48c'
down_revision: Union[str, Sequence[str], None] = 'e48b8466dc89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'embedding')
    # ### end Alembic commands ###
